module.exports=[
    {
        id:1,
        name:'Alex',
        team:'team',
        position:'position',
        emailAdress:'emailAdress',
        phoneNumber:'phoneNumber',
        birthday:'birthday',
        profileImage:'profileImage'
    },
    {
        id:2,
        name:'GG',
        team:'team',
        position:'position',
        emailAdress:'emailAdress',
        phoneNumber:'phoneNumber',
        birthday:'birthday',
        profileImage:'profileImage'
    },
    {
        id:3,
        name:'Hailey',
        team:'team',
        position:'position',
        emailAdress:'emailAdress',
        phoneNumber:'phoneNumber',
        birthday:'birthday',
        profileImage:'profileImage'
    },
]